export const TokenType = {
  SPACE: 'SPACE',
  COLON: 'COLON',
  LEFT_PAREN: 'LEFT_PAREN',
  RIGHT_PAREN: 'RIGHT_PAREN',
  LEFT_BRACE: 'LEFT_BRACE',
  RIGHT_BRACE: 'RIGHT_BRACE',
  WORD: 'WORD',
  OR: 'OR',
  AND: 'AND',
  QUOTE: 'QUOTE',
  MINUS: 'MINUS',
  PUNCTUATION: 'PUNCTUATION'
};